query ItemById(
  $catalogSellerId: String
  $semStoreId: Int
  $postalAddress: PostalAddress
  $itemId: String!
  $selected: Boolean
  $variantFieldId: String
  $storeFrontIds: [StoreFrontId]
  $p13N: P13NRequest
  $fulfillmentIntent: String
) {
  product(
    catalogSellerId: $catalogSellerId
    itemId: $itemId
    postalAddress: $postalAddress
    storeFrontIds: $storeFrontIds
    selected: $selected
    semStoreId: $semStoreId
    p13N: $p13N
    variantFieldId: $variantFieldId
    fulfillmentIntent: $fulfillmentIntent
  ) {
    ...FullProductFragment
  }
}
fragment FullProductFragment on Product {
  blitzItem
  giftingEligibility
  shipAsIs
  subscriptionEligible
  showFulfillmentLink
  additionalOfferCount
  shippingRestriction
  availabilityStatus
  averageRating
  suppressReviews
  brand
  badges {
    ...BadgesFragment
  }
  rhPath
  partTerminologyId
  aaiaBrandId
  manufacturerProductId
  productTypeId
  tireSize
  tireLoadIndex
  tireSpeedRating
  viscosity
  model
  buyNowEligible
  earlyAccessEvent
  showBuyWithWplus
  preOrder {
    ...PreorderFragment
  }
  canonicalUrl
  catalogSellerId
  sellerReviewCount
  sellerAverageRating
  category {
    ...ProductCategoryFragment
  }
  classType
  classId
  fulfillmentTitle
  shortDescription
  fulfillmentType
  fulfillmentBadge
  checkStoreAvailabilityATC
  fulfillmentLabel {
    checkStoreAvailability
    wPlusFulfillmentText
    message
    shippingText
    fulfillmentText
    locationText
    fulfillmentMethod
    addressEligibility
    fulfillmentType
    postalCode
  }
  hasSellerBadge
  itemType
  id
  imageInfo {
    ...ProductImageInfoFragment
  }
  location {
    postalCode
    stateOrProvinceCode
    city
    storeIds
  }
  manufacturerName
  name
  numberOfReviews
  orderMinLimit
  orderLimit
  offerId
  offerType
  priceInfo {
    priceDisplayCodes {
      ...PriceDisplayCodesFragment
    }
    currentPrice {
      ...ProductPriceFragment
    }
    wasPrice {
      ...ProductPriceFragment
    }
    unitPrice {
      ...ProductPriceFragment
    }
    savings {
      priceString
    }
    subscriptionPrice {
      price
      priceString
      intervalFrequency
      duration
      percentageRate
      subscriptionString
    }
    priceRange {
      minPrice
      maxPrice
      priceString
      currencyUnit
      unitOfMeasure
      denominations {
        price
        priceString
        selected
      }
    }
  }
  returnPolicy {
    returnable
    freeReturns
    returnWindow {
      value
      unitType
    }
  }
  fsaEligibleInd
  sellerId
  sellerName
  sellerDisplayName
  secondaryOfferPrice {
    currentPrice {
      priceType
      priceString
      price
    }
  }
  semStoreData {
    pickupStoreId
    deliveryStoreId
    isSemLocationDifferent
  }
  shippingOption {
    ...ShippingOptionFragment
  }
  type
  pickupOption {
    slaTier
    accessTypes
    availabilityStatus
    storeName
    storeId
  }
  salesUnit
  usItemId
  variantCriteria {
    id
    categoryTypeAllValues
    name
    type
    variantList {
      availabilityStatus
      id
      images
      name
      products
      swatchImageUrl
      selected
    }
  }
  variants {
    ...MinimalProductFragment
  }
  groupMetaData {
    groupType
    groupSubType
    numberOfComponents
    groupComponents {
      quantity
      offerId
      componentType
      productDisplayName
    }
  }
  upc
  wfsEnabled
  sellerType
  ironbankCategory
  snapEligible
  showAddOnServices
  addOnServices {
    serviceType
    serviceTitle
    serviceSubTitle
    groups {
      groupType
      groupTitle
      assetUrl
      shortDescription
      services {
        displayName
        offerId
        selectedDisplayName
        currentPrice {
          price
          priceString
        }
      }
    }
  }
  productLocation {
    displayValue
  }
}
fragment BadgesFragment on UnifiedBadge {
  flags {
    __typename
    ... on BaseBadge {
      id
      text
      key
      query
      type
    }
    ... on PreviouslyPurchasedBadge {
      id
      text
      key
      lastBoughtOn
      numBought
      criteria {
        name
        value
      }
    }
  }
  labels {
    __typename
    ... on BaseBadge {
      id
      text
      key
    }
    ... on PreviouslyPurchasedBadge {
      id
      text
      key
      lastBoughtOn
      numBought
    }
  }
  tags {
    __typename
    ... on BaseBadge {
      id
      text
      key
    }
  }
}
fragment ShippingOptionFragment on ShippingOption {
  accessTypes
  availabilityStatus
  slaTier
  deliveryDate
  maxDeliveryDate
  shipMethod
  shipPrice {
    ...ProductPriceFragment
  }
}
fragment ProductCategoryFragment on ProductCategory {
  categoryPathId
  path {
    name
    url
  }
}
fragment PreorderFragment on PreOrder {
  streetDate
  streetDateDisplayable
  streetDateType
  isPreOrder
  preOrderMessage
  preOrderStreetDateMessage
}
fragment MinimalProductFragment on Variant {
  availabilityStatus
  imageInfo {
    ...ProductImageInfoFragment
  }
  priceInfo {
    priceDisplayCodes {
      ...PriceDisplayCodesFragment
    }
    currentPrice {
      ...ProductPriceFragment
    }
    wasPrice {
      ...ProductPriceFragment
    }
    unitPrice {
      ...ProductPriceFragment
    }
  }
  productUrl
  usItemId
  id: productId
  fulfillmentBadge
}
fragment ProductImageInfoFragment on ProductImageInfo {
  allImages {
    id
    url
    zoomable
  }
  thumbnailUrl
}
fragment PriceDisplayCodesFragment on PriceDisplayCodes {
  clearance
  eligibleForAssociateDiscount
  finalCostByWeight
  hidePriceForSOI
  priceDisplayCondition
  pricePerUnitUom
  reducedPrice
  rollback
  strikethrough
  submapType
  unitOfMeasure
  unitPriceDisplayCondition
}
fragment ProductPriceFragment on ProductPrice {
  price
  priceString
  variantPriceString
  priceType
  currencyUnit
}
