query Search(
  $query: String
  $page: Int
  $prg: Prg!
  $facet: String
  $sort: Sort = best_match
  $catId: String
  $max_price: String
  $min_price: String
  $spelling: Boolean = true
  $affinityOverride: AffinityOverride
  $storeSlotBooked: String
  $ps: Int
  $ptss: String
  $recall_set: String
  $trsp: String
  $additionalQueryParams: JSON = {}
) {
  search(
    query: $query
    page: $page
    prg: $prg
    facet: $facet
    sort: $sort
    cat_id: $catId
    max_price: $max_price
    min_price: $min_price
    spelling: $spelling
    affinityOverride: $affinityOverride
    storeSlotBooked: $storeSlotBooked
    ps: $ps
    ptss: $ptss
    recall_set: $recall_set
    trsp: $trsp
    additionalQueryParams: $additionalQueryParams
  ) {
    query
    searchResult {
      ...SearchResultFragment
    }
  }
}
fragment SearchResultFragment on SearchInterface {
  query
  _prefetch_
  title
  aggregatedCount
  ...BreadCrumbFragment
  ...DebugFragment
  ...ItemStacksFragment
  ...PageMetaDataFragment
  ...PaginationFragment
  ...SpellingFragment
  ...RequestContextFragment
  ...ErrorResponse
  modules {
    facetsV1 {
      ...FacetFragment
    }
    guidedNavigation {
      ...GuidedNavFragment
    }
    guidedNavigationV2 {
      ...PillsModuleFragment
    }
    pills {
      ...PillsModuleFragment
    }
    spellCheck {
      title
      subTitle
      urlLinkText
      url
    }
  }
}
fragment BreadCrumbFragment on SearchInterface {
  breadCrumb {
    id
    name
    url
  }
}
fragment DebugFragment on SearchInterface {
  debug {
    sisUrl
  }
}
fragment ItemStacksFragment on SearchInterface {
  itemStacks {
    displayMessage
    meta {
      adsBeacon {
        adUuid
        moduleInfo
        max_ads
      }
      query
      stackId
      stackType
      title
      layoutEnum
      totalItemCount
      totalItemCountDisplay
      viewAllParams {
        query
        cat_id
        sort
        facet
        affinityOverride
        recall_set
        min_price
        max_price
      }
    }
    itemsV2 {
      ...ItemFragment
      ...InGridMarqueeAdFragment
    }
  }
}
fragment ItemFragment on Product {
  __typename
  id
  usItemId
  fitmentLabel
  name
  type
  shortDescription
  imageInfo {
    ...ProductImageInfoFragment
  }
  canonicalUrl
  externalInfo {
    url
  }
  category {
    path {
      name
      url
    }
  }
  badges {
    flags {
      key
      text
    }
    tags {
      ... on BaseBadge {
        key
        text
        type
      }
    }
  }
  classType
  averageRating
  numberOfReviews
  esrb
  mediaRating
  salesUnitType
  sellerId
  sellerName
  hasSellerBadge
  availabilityStatusV2 {
    display
    value
  }
  productLocation {
    displayValue
    aisle {
      zone
      aisle
    }
  }
  badge {
    type
    dynamicDisplayName
  }
  fulfillmentSpeed
  offerId
  preOrder {
    ...PreorderFragment
  }
  priceInfo {
    ...ProductPriceInfoFragment
  }
  variantCriteria {
    ...VariantCriteriaFragment
  }
  fulfillmentBadge
  fulfillmentTitle
  fulfillmentType
  brand
  manufacturerName
  showAtc
  sponsoredProduct {
    spQs
    clickBeacon
    spTags
  }
  showOptions
}
fragment ProductImageInfoFragment on ProductImageInfo {
  thumbnailUrl
}
fragment ProductPriceInfoFragment on ProductPriceInfo {
  priceRange {
    minPrice
    maxPrice
  }
  currentPrice {
    ...ProductPriceFragment
  }
  wasPrice {
    ...ProductPriceFragment
  }
  unitPrice {
    ...ProductPriceFragment
  }
  listPrice {
    ...ProductPriceFragment
  }
  shipPrice {
    ...ProductPriceFragment
  }
  subscriptionPrice {
    priceString
    subscriptionString
  }
  priceDisplayCodes {
    priceDisplayCondition
    finalCostByWeight
  }
}
fragment PreorderFragment on PreOrder {
  isPreOrder
  preOrderMessage
  preOrderStreetDateMessage
}
fragment ProductPriceFragment on ProductPrice {
  price
  priceString
}
fragment VariantCriteriaFragment on VariantCriterion {
  name
  type
  id
  isVariantTypeSwatch
  variantList {
    id
    images
    name
    rank
    swatchImageUrl
    availabilityStatus
    products
    selectedProduct {
      canonicalUrl
      usItemId
    }
  }
}
fragment InGridMarqueeAdFragment on MarqueePlaceholder {
  __typename
  type
  moduleLocation
  lazy
}
fragment PageMetaDataFragment on SearchInterface {
  pageMetadata {
    title
    canonical
    description
    location {
      addressId
      postalCode
    }
  }
}
fragment PaginationFragment on SearchInterface {
  paginationV2 {
    maxPage
    pageProperties
  }
}
fragment SpellingFragment on SearchInterface {
  spelling {
    correctedTerm
  }
}
fragment RequestContextFragment on SearchInterface {
  requestContext {
    isFitmentFilterQueryApplied
    searchMatchType
    categories {
      id
      name
    }
  }
}
fragment ErrorResponse on SearchInterface {
  errorResponse {
    correlationId
    source
    errors {
      errorType
      statusCode
      statusMsg
      source
    }
  }
}
fragment GuidedNavFragment on GuidedNavigationSearchInterface {
  title
  url
}
fragment PillsModuleFragment on PillsSearchInterface {
  title
  url
  image: imageV1 {
    src
    alt
  }
  baseSeoURL
}
fragment FacetFragment on Facet {
  name
  type
  layout
  min
  max
  selectedMin
  selectedMax
  unboundedMax
  stepSize
  values {
    id
    name
    description
    type
    itemCount
    isSelected
    baseSeoURL
  }
}
